// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://fsyxxhgxiwstqhswtssx.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzeXh4aGd4aXdzdHFoc3d0c3N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAzOTQzNjQsImV4cCI6MjA0NTk3MDM2NH0.xN08zbd4i8wykK6KwgJH2physC1nNrwaZ7JgZb0jqVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);